Protocolo/Protocolo/Controllers/CadastroDeProtocoloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Protocolo.Controllers
{
    public class CadastroDeProtocoloController : Controller
    {
        // GET: CadastroDeProtocolo
        public ActionResult Cadastrar()
        {


              

                return View();

          

            
        }

        public ActionResult InseriProtocolo(FormCollection protocolo)
        {


            String protocolobusca = protocolo["protocolo"];
            string pt = "";
            string ano = "";
            bool barra = true;

            for (int i = 0; i < protocolobusca.Length; i++)
            {
                if (protocolobusca[i] != '/' && barra)
                {
                    pt = pt + protocolobusca[i];

                }
                else
                {
                    ano = ano + protocolobusca[i];
                    barra = false;

                }
            }


            Models.Protocolo PROTOCOLO = new Models.Protocolo() {

                protocolo = pt,
                ano =ano.Replace("/",""),
            };

            Models.Protocolo.InserirProtocolo(PROTOCOLO);
            return View("CADASTRAR");


        }
    }
}

Protocolo/Protocolo/Views/CadastroDeProtocolo/cadastrar.cshtml
@{
    ViewBag.Title = "CadastroProtocolo";
}

<h2>Cadastro Protocolo</h2>

<body>

    <div class="row">
        <div class="col-md-4"></div>

        <div class="col-md-4">
            <h4>Cadastro de protocolo:</h4>


            @using (Html.BeginForm("InseriProtocolo", "CadastroDeProtocolo", FormMethod.Post))
            {
                <input type="text" placeholder="Exemplo:1/2017" name="protocolo" class="form-control" />
                <p>
                    <input type="submit" value="Salvar:" class="form-control" />
                    <label class="col-md-8">@ViewBag.messagem</label>
                </p>

            }
        </div>   
        <div class="col-md-4"></div>    
    </div>
</body>